# название workflow
name: pw tests

# когда мы запускаем автотесты
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  # ручной запуск автотестов
  workflow_dispatch:

jobs:
  e2eTests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Проверка версии Node.js
        run: node -v

      - name: Установить PW
        run: npx playwright install --with-deps

      - name: Запустить PW
        run: npx playwright test tests/
    
